Repository openshift/ci-docs, pull requests merged in 2022-11, with the labels that each got.

#305 Doc a pitfall upon pool renaming
  content/en/docs/how-tos/cluster-claim.md
Labels: approved, lgtm, tide/merge-method-squash

#306 Update to reference the `pj-rehearse` external prow plugin
  content/en/docs/how-tos/contributing-openshift-release.md
Labels: approved, lgtm, tide/merge-method-squash

#307 cluster pools: add #standby for pools
  content/en/docs/how-tos/cluster-claim.md
  layouts/partials/head.html
Labels: approved, lgtm

#308 feat: updated docs to mention new automation for disruption data
  content/en/docs/release-oversight/disruption-testing/data-architecture.md
  static/disruption_test_diagram.svg
Labels: approved, lgtm

#309 useful-links: use public presentation links
  content/en/docs/getting-started/useful-links.md
Labels: approved, lgtm

#311 `pj-rehearse` plugin: note that the 'rehearsals-ack' label is necessary for merge
  content/en/docs/how-tos/contributing-openshift-release.md
Labels: approved, lgtm

#301 how-tos: update login instructions
  content/en/docs/how-tos/interact-with-running-jobs.md
Labels: approved, lgtm

#312 `pj-rehearse`: add information about the new 'reject' and 'refresh' commands
  content/en/docs/how-tos/contributing-openshift-release.md
Labels: approved, lgtm

#315 Mirror images with wildcard
  content/en/docs/how-tos/mirroring-to-quay.md
Labels: approved, lgtm

#314 `pr-reminder`: reference new config location
  content/en/docs/how-tos/pr-reminder.md
Labels: approved, lgtm

#316 Specify that `pj-rehearse` reacts to PR body description and comments
  content/en/docs/how-tos/contributing-openshift-release.md
Labels: approved, lgtm

#317 observer-pods: adding timeout and grace_period
  content/en/docs/architecture/ci-operator-internals/observer-pods.md
Labels: approved, lgtm, ok-to-test
