Repository openshift/ci-docs, pull requests merged in 2022-08, with the labels that each got.

#275 artifacts: fix link
  content/en/docs/how-tos/artifacts.md
Labels: approved, lgtm

#278 content/en/docs/getting-started/useful-links: Link arm64 release controller
  content/en/docs/getting-started/useful-links.md
Labels: approved, lgtm

#276 `pr-reminder`: add how-to doc
  content/en/docs/how-tos/pr-reminder.md
  static/pr-reminder.png
Labels: approved, lgtm, tide/merge-method-squash

#277 doc: update information on when job primer runs
  content/en/docs/release-oversight/disruption-testing/job-primer.md
Labels: approved, lgtm

#279 document how to turn off the SA/kubeconfig
  content/en/docs/architecture/step-registry.md
Labels: approved, lgtm

#281 fix typo in doc
  content/en/docs/how-tos/pr-reminder.md
Labels: approved, lgtm

#282 ci-operator: document publishing by commit hash
  content/en/docs/architecture/ci-operator.md
Labels: approved, lgtm

#268 retester: Added config file
  content/en/docs/architecture/retester.md
Labels: approved, lgtm, ok-to-test, tide/merge-method-squash

#284 Add a warning about mirroring from docker.io
  content/en/docs/how-tos/external-images.md
Labels: approved, lgtm

#285 Add info about time required to sync rover groups
  content/en/docs/how-tos/rbac.md
Labels: approved, lgtm

#288 Remove references to the old retester
  content/en/docs/architecture/retester.md
Labels: approved, lgtm
