Repository openshift/ci-docs, pull requests merged in 2023-11, with the labels that each got.

#399 content/en/docs/how-tos/onboarding-a-new-component: Self-checks for image presence
  content/en/docs/how-tos/onboarding-a-new-component.md
Labels: approved, lgtm

#400 Fix cluster's description
  layouts/partials/head.html
Labels: approved, lgtm

#401 Add info about cluster pools/profiles
  content/en/docs/how-tos/onboarding-a-new-component.md
Labels: approved, lgtm

#404 Clarify the usage of the cluster field
  content/en/docs/how-tos/contributing-openshift-release.md
Labels: approved, lgtm

#403 Add psalajova to owners
  OWNERS
Labels: approved, lgtm

#402 Add private cluster profiles section
  content/en/docs/how-tos/adding-a-cluster-profile.md
Labels: approved, lgtm

#406 Fix issue DPTP-3750 Add section for preparing cloud accounts
  content/en/docs/how-tos/adding-a-cluster-profile.md
Labels: approved, lgtm

#407 Pipelines howto
  content/en/docs/how-tos/creating-a-pipeline.md
Labels: approved, lgtm

#408 add info about manually submitting `PRPQR` spec with multiple PRs provided
  content/en/docs/release-oversight/payload-testing.md
Labels: approved, lgtm

#410 add info about manually submitting PRPQR spec
  content/en/docs/release-oversight/payload-testing.md
Labels: approved, lgtm

#411 Clarify adding a secret instructions
  content/en/docs/how-tos/adding-a-new-secret-to-ci.md
Labels: approved, lgtm

#409 The image registry on app.ci is deprecated
  content/en/docs/how-tos/use-registries-in-build-farm.md
  layouts/partials/head.html
Labels: approved, lgtm, tide/merge-method-squash

#413 Fix some typos
  content/en/docs/how-tos/use-registries-in-build-farm.md
Labels: approved, lgtm

#412 Fix issue DPTP-3750 Add missing permissions for preparing cloud accounts
  content/en/docs/how-tos/adding-a-cluster-profile.md
Labels: approved, lgtm, tide/merge-method-rebase

#416 Generate Hypershift's supported versions
  content/en/docs/architecture/ci-operator.md
  layouts/partials/head.html
Labels: approved, lgtm

#418 Add a note about Hypershift's supported versions
  content/en/docs/architecture/ci-operator.md
Labels: approved, lgtm
